source 'https://rubygems.org'

ruby '1.9.3'

gem "uglifier"
gem "newrelic_rpm"
gem "sass"
gem "compass"
gem "coffee-script"
gem "jekyll" # we need at least this version so jekyll will use Ruby 1.9.2
gem "jekyll-assets"
gem "rake"                # actually not need for heroku but for the provided Rakefile
gem "RedCloth"           
gem "sinatra"
gem "unicorn"
gem "rack-jekyll"
gem "foreman"             # this is a tool to test and use the Procfile locally
